### PR TITLE
Please review code for barebones app

### PR DESCRIPTION
**Pull request by tbright7**

### CODE REVIEW

**Comment by guoguoying2013** [comment]
Looks good!

**Review by guoguoying2013 — APPROVED** [review]
Looks good officially : )

**Review by ecetino — APPROVED** [review]
For some reason. I only see a pull request for the client/src/index.js but I looked at the rest and it looks good. Consider saving webpack and webpack-cli as a dev dependency next time (using --save -dev) since it will only be used by a developer.

**Review by loganrosenlund37 — APPROVED** [review]
Looks good!

**Pull request closed without merging**
